### ISSUE TITLE
Form inputs with uneven widths

### ISSUE THREAD

**Issue by CasperBraske** [woocommerce/storefront#1144]
`.col2-set .form-row-first` and `.col2-set .form-row-last` have very different widths in the CSS yielding uneven measures.

```css
.col2-set .form-row-first {
	width: 33.3333333333%;
	float: left;
	margin-right: 11.1111111111%;
}
```
```css
.col2-set .form-row-last {
	width: 55.5555555556%;
	float: right;
	margin-right: 0;
}
```

![image](https://user-images.githubusercontent.com/700448/58329144-39712580-7e0a-11e9-9b9a-f79030af267d.png)
