### ISSUE TITLE
Sensei course thumbnails have no margin

### ISSUE THREAD

**Issue by aheckler** [woocommerce/storefront#668]
From 722246-zen and repro'd on my test site.

If I have Sensei on a site using Storefront, and I'm looking at the My Courses page, the course thumbnail doesn't have a right margin. Screenshot:

<img width="526" alt="screen shot 2017-10-09 at 3 25 01 pm" src="https://user-images.githubusercontent.com/5512652/31354867-08b4e872-ad06-11e7-966d-725478da838d.png">

I can fix it with this:

```css
body.sensei #content #sensei-user-courses .course-container a img.thumbnail {
	margin-right: 1em;
}
```

... but since I'm not sure that's the best solution, I thought I'd post here.
