### ISSUE TITLE
Extra space after set products per row to 3

### ISSUE THREAD

**Issue by CarlGalloy** [woocommerce/storefront#772]
Hi
I just try use Storefront template. 
See every things is god except one things. i want user three column for shewing product on home page. but we have extra space on last image .
How can i fix this problem? want to have a big images. like [this site](http://www.rusticmodern.net/shop/?v=89d269ea9f2e)

Also search on google and find a solutions like using this css:(but nothings changed)

```css
.woocommerce ul.products li.first,
.woocommerce-page ul.products li.first {
  clear: none;
}
.woocommerce ul.products li.last,
.woocommerce-page ul.products li.last {
  margin-right: 3% !important;
}
.woocommerce ul.products li:nth-child(3),
.woocommerce-page ul.products li:nth-child(3) {
  margin-right: 0% !important;
}
```
